### ISSUE TITLE
nilaway panic: interface conversion / send on closed channel

### ISSUE THREAD

**Issue by anodar** [uber-go/nilaway#100]
Here's the full trace:

```bash
$ nilaway ./...
panic: interface conversion: types.Object is *types.Var, not *types.Func [recovered]
	panic: send on closed channel

goroutine 172328 [running]:
go.uber.org/nilaway/assertion/function.analyzeFunc.func1()
	/home/user/.gvm/pkgsets/go1.20/global/pkg/mod/go.uber.org/nilaway@v0.0.0-20231031155528-970a3b8379e3/assertion/function/analyzer.go:457 +0x11e
panic({0x7972e0, 0xc1a7b6e210})
	/home/user/.gvm/gos/go1.20/src/runtime/panic.go:884 +0x213
go.uber.org/nilaway/assertion/function/assertiontree.exprAsAssignmentConsumer.func3({0x878f68, 0xc071ea71c0})
	/home/user/.gvm/pkgsets/go1.20/global/pkg/mod/go.uber.org/nilaway@v0.0.0-20231031155528-970a3b8379e3/assertion/function/assertiontree/backprop_util.go:487 +0x955
go.uber.org/nilaway/assertion/function/assertiontree.exprAsAssignmentConsumer(0xc0e871b500, {0x878650?, 0xc071ea4900}, {0x0?, 0x0})
	/home/user/.gvm/pkgsets/go1.20/global/pkg/mod/go.uber.org/nilaway@v0.0.0-20231031155528-970a3b8379e3/assertion/function/assertiontree/backprop_util.go:593 +0x679
go.uber.org/nilaway/assertion/function/assertiontree.backpropAcrossSend(0x878650?, 0xc071ea4900)
	/home/user/.gvm/pkgsets/go1.20/global/pkg/mod/go.uber.org/nilaway@v0.0.0-20231031155528-970a3b8379e3/assertion/function/assertiontree/backprop.go:126 +0xb3
go.uber.org/nilaway/assertion/function/assertiontree.backpropAcrossNode(0x0?, {0x878650?, 0xc071ea4900?})
	/home/user/.gvm/pkgsets/go1.20/global/pkg/mod/go.uber.org/nilaway@v0.0.0-20231031155528-970a3b8379e3/assertion/function/assertiontree/backprop.go:76 +0x12f
go.uber.org/nilaway/assertion/function/assertiontree.backpropAcrossBlock(0xc0e871b500, 0xc0e6ae8d80)
	/home/user/.gvm/pkgsets/go1.20/global/pkg/mod/go.uber.org/nilaway@v0.0.0-20231031155528-970a3b8379e3/assertion/function/assertiontree/backprop.go:42 +0x9a
go.uber.org/nilaway/assertion/function/assertiontree.BackpropAcrossFunc({0x879e20, 0xc19991d410}, 0x466fee?, 0xc071ea49c0, {0xc071ea49c0, 0x0, 0xc07f7b08f0, 0xc19991d710, 0xc19991d6e0, 0xc19991d3e0, ...}, ...)
	/home/user/.gvm/pkgsets/go1.20/global/pkg/mod/go.uber.org/nilaway@v0.0.0-20231031155528-970a3b8379e3/assertion/function/assertiontree/backprop.go:857 +0x8de
go.uber.org/nilaway/assertion/function.analyzeFunc({0x879e20?, 0xc19991d410?}, 0xc07f7b08f0, 0xc071ea49c0, {0xc071ea49c0, 0x0, 0xc07f7b08f0, 0xc19991d710, 0xc19991d6e0, 0xc19991d3e0, ...}, ...)
	/home/user/.gvm/pkgsets/go1.20/global/pkg/mod/go.uber.org/nilaway@v0.0.0-20231031155528-970a3b8379e3/assertion/function/analyzer.go:463 +0x11e
created by go.uber.org/nilaway/assertion/function.run
	/home/user/.gvm/pkgsets/go1.20/global/pkg/mod/go.uber.org/nilaway@v0.0.0-20231031155528-970a3b8379e3/assertion/function/analyzer.go:208 +0x11ca
```

**Comment by yuxincs** [comment]
Thanks for the report! 

NilAway in general should _never_ panic (we have panic recovery handler at the entry point to convert the panic to diagnostics for debugging purposes, but we should _never_ panic). 

We have a fix for `panic: send on closed channel` and I'll create a PR shortly. 

Meanwhile, it would be interesting to know what code triggered the panic:

```
interface conversion: types.Object is *types.Var, not *types.Func
```

If possible, would you mind sharing a code piece? it would help us fix the real root cause :)
