### ISSUE TITLE
Panic with golang.org/x/tools v0.19.0

### ISSUE THREAD

**Issue by kpaulisse** [uber-go/nilaway#213]
I have nilaway integrated into my project via bazel and nogo. With version v0.18.0 of `golang.org/x/tools` everything works fine. However when this got updated to `v0.19.0` it now causes a panic.

```
goroutine 127 [running]:
go/types.(*Named).Obj(...)
	GOROOT/src/go/types/named.go:295
golang.org/x/tools/go/analysis/passes/internal/analysisutil.IsNamedType({0x10561fc40?, 0x0?}, {0x10543a414, 0x8}, {0x14001e1ab28, 0x1, 0x1059f2b38?})
	external/org_golang_x_tools/go/analysis/passes/internal/analysisutil/util.go:123 +0x44
golang.org/x/tools/go/analysis/passes/httpresponse.isHTTPFuncOrMethodOnClient(0x140001a8fc0, 0x0?)
	external/org_golang_x_tools/go/analysis/passes/httpresponse/httpresponse.go:122 +0xfc
golang.org/x/tools/go/analysis/passes/httpresponse.run.func1({0x10561f628?, 0x140005f98c0?}, 0x18?, {0x14003192000, 0x5, 0x10})
	external/org_golang_x_tools/go/analysis/passes/httpresponse/httpresponse.go:62 +0x58
golang.org/x/tools/go/ast/inspector.(*Inspector).WithStack(0x14001382300, {0x14001e1ad08?, 0x10592aae0?, 0x14002c00008?}, 0x14001e1ad18)
	external/org_golang_x_tools/go/ast/inspector/inspector.go:148 +0x160
golang.org/x/tools/go/analysis/passes/httpresponse.run(0x14003184270)
	external/org_golang_x_tools/go/analysis/passes/httpresponse/httpresponse.go:57 +0x104
main.(*action).execOnce(0x140000b7e00)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:353 +0x768
sync.(*Once).doSlow(0x0?, 0x0?)
	GOROOT/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
	GOROOT/src/sync/once.go:65
main.(*action).exec(...)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:280
main.execAll.func1(0x0?)
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:274 +0x74
created by main.execAll in goroutine 1
	external/io_bazel_rules_go/go/tools/builders/nogo_main.go:272 +0x4c
```

**Comment by kpaulisse** [comment]
Sorry for the noise, as this appears to be a problem in `nogo` and not `nilaway`. I'll close the issue.
